### ISSUE TITLE
doesnt work on 1.16.3

### ISSUE THREAD

**Issue by Apmunute** [QuadraticKid/MC-ChatParsing#4]
![image](https://user-images.githubusercontent.com/26578250/97001754-44ece280-150f-11eb-9e75-fd645dbb836c.png)
help

**Comment by Apmunute** [comment]
it doesn't reset the colors + the %s thing

**Comment by Apmunute** [comment]
managed to fix %s by myself but still gives the reset thing

**Comment by QuadraticKid** [comment]
i'll look into it in a bit when i'm home

**Comment by QuadraticKid** [comment]
Try updating translations.json to 1.16.3 mappings.

**Comment by QuadraticKid** [comment]
Bug appears to be with minecraft-protocol
